# Generated by Django 4.2.3 on 2023-07-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30, verbose_name='proxy address')),
                ('ip', models.CharField(max_length=30, verbose_name='proxy ip')),
                ('is_working', models.BooleanField(default=False, editable=False, verbose_name='آیا پراکسی فعال است؟')),
                ('response_text', models.TextField(default='-', editable=False, verbose_name='داده های دریافت شده توسط پراکسی')),
            ],
            options={
                'verbose_name': 'پروکسی',
                'verbose_name_plural': 'پروکسی',
            },
        ),
    ]
