# Generated by Django 4.2.3 on 2023-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name': 'پروکسی', 'verbose_name_plural': 'پروکسی ها'},
        ),
        migrations.RenameField(
            model_name='proxy',
            old_name='ip',
            new_name='proxy_ip',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='address',
        ),
        migrations.AddField(
            model_name='proxy',
            name='proxy_port',
            field=models.CharField(default=1, max_length=30, verbose_name='proxy port'),
            preserve_default=False,
        ),
    ]
