# Generated by Django 4.2.3 on 2023-07-17 14:40

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(blank=True, max_length=255, null=True, verbose_name='نماد سازمان')),
                ('link', models.URLField(blank=True, max_length=2000, null=True, verbose_name='لینک جزئیات سازمان')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام سازمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=255, verbose_name='نماد')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'لینک شرکت',
                'verbose_name_plural': 'لینک های شرکت ها',
                'ordering': ['badge'],
            },
        ),
        migrations.CreateModel(
            name='ConfigSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.PositiveSmallIntegerField(default=60, verbose_name='زمان توقف ربات بین هر کوئری')),
                ('is_proxy_on', models.BooleanField(default=True, verbose_name='پراکسی فعال باشد؟')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='IsRobotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.PositiveSmallIntegerField(editable=False, unique=True, verbose_name='id')),
                ('is_robot_run', models.BooleanField(default=False, editable=False, verbose_name='آیا ربات در حال اجراست؟')),
            ],
            options={
                'verbose_name': 'robot check',
                'verbose_name_plural': 'robot checks',
            },
        ),
        migrations.CreateModel(
            name='SeasonalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255, verbose_name='موضوع گزارش')),
                ('report_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='لینک گزارش')),
                ('reported_percentage', models.FloatField(blank=True, max_length=255, null=True, verbose_name='درصد گزارش شده')),
                ('reported_percentage_color', models.CharField(blank=True, max_length=255, null=True, verbose_name='رنگ درصد')),
                ('season_reported_date', models.CharField(max_length=255, verbose_name='گزارش فصلی چند ماهه منتهی به تاریخ')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('is_finished', models.BooleanField(default=False, verbose_name='آیا این گزارش کامل شده است؟')),
                ('is_acceptable', models.BooleanField(default=False, verbose_name='آیا این گزارش با فرمت های طراحی شده سازگار است؟')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codal.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'گزارش فصلی',
                'verbose_name_plural': 'گزارش فصلی',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=255, verbose_name='موضوع گزارش')),
                ('report_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='لینک گزارش')),
                ('reported_number', models.IntegerField(blank=True, null=True, verbose_name='عدد گزارش')),
                ('month_reported_date', models.CharField(max_length=255, verbose_name='گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به تاریخ')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
                ('is_finished', models.BooleanField(default=False, verbose_name='آیا این گزارش کامل شده است؟')),
                ('is_acceptable', models.BooleanField(default=False, verbose_name='آیا این گزارش با فرمت های طراحی شده سازگار است؟')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codal.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'گزارش مالی ماهانه',
                'verbose_name_plural': 'گزارشات مالی ماهانه',
                'ordering': ['-updated_at'],
            },
        ),
    ]
