# Generated by Django 4.2.3 on 2023-07-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsRobotRun',
        ),
    ]
