# Generated by Django 4.2.3 on 2023-07-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0002_delete_isrobotrun'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-updated_at'], 'verbose_name': 'گزارش ماهانه', 'verbose_name_plural': 'گزارشات ماهانه'},
        ),
    ]
