# Generated by Django 4.2.3 on 2023-07-18 10:57

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0003_alter_monthlyreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['month_reported_date'], 'verbose_name': 'گزارش ماهانه', 'verbose_name_plural': 'گزارشات ماهانه'},
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='report_has_sent_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 7, 18, 10, 57, 35, 81373), verbose_name='تاریخ و زمان ارسال گزارش توسط کدال'),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='report_has_sent_at',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 7, 18, 10, 57, 35, 82376), verbose_name='تاریخ و زمان ارسال گزارش توسط کدال'),
        ),
    ]
