# Generated by Django 4.2.3 on 2023-07-18 14:09

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0004_alter_monthlyreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='report_has_sent_at',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان ارسال گزارش توسط کدال'),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='report_has_sent_at',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ و زمان ارسال گزارش توسط کدال'),
        ),
    ]
