# Generated by Django 4.2.3 on 2023-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0005_alter_monthlyreport_report_has_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalreport',
            name='gross_profit_and_loss',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='سود و زیان ناخالص'),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='operating_income',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='درآمد های عملیاتی'),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='report_time_period',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='گزارش چند ماهه'),
        ),
    ]
