# Generated by Django 4.2.3 on 2023-07-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0006_seasonalreport_gross_profit_and_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='report_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وضعیت گزارش'),
        ),
        migrations.AddField(
            model_name='seasonalreport',
            name='report_status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='وضعیت گزارش'),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='report_time_period',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='گزارش چند ماهه'),
        ),
    ]
