# Generated by Django 4.2.3 on 2023-07-18 17:02

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0007_monthlyreport_report_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month_reported_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2023, 7, 18), verbose_name='گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به تاریخ'),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='season_reported_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2023, 7, 18), verbose_name='گزارش فصلی چند ماهه منتهی به تاریخ'),
        ),
    ]
