# Generated by Django 4.2.3 on 2023-07-18 17:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0008_alter_monthlyreport_month_reported_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month_reported_date',
            field=django_jalali.db.models.jDateField(verbose_name='گزارش فعالیت ماهانه دوره ۱ ماهه منتهی به تاریخ'),
        ),
        migrations.AlterField(
            model_name='seasonalreport',
            name='season_reported_date',
            field=django_jalali.db.models.jDateField(verbose_name='گزارش فصلی چند ماهه منتهی به تاریخ'),
        ),
    ]
