# Generated by Django 4.2.3 on 2023-07-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0009_alter_monthlyreport_month_reported_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'ordering': ['-month_reported_date'], 'verbose_name': 'گزارش ماهانه', 'verbose_name_plural': 'گزارشات ماهانه'},
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_monthly_report_ready', models.BooleanField(default=False, verbose_name='آیا برای این شرکت گزارشات ماهانه قابل ارائه است؟')),
                ('is_seasonal_report_ready', models.BooleanField(default=False, verbose_name='آیا برای این شرکت گزارشات فصلی قابل ارائه است؟')),
                ('date_finished', models.DateField(blank=True, null=True, verbose_name='زمان پایان عملیات')),
                ('monthly_report_1_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ آخرین گزارش ماهانه موجود')),
                ('monthly_report_2_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ گزارش ماهانه یکی مانده به آخر')),
                ('monthly_report_3_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ گزارش ماهانه دوتا مانده به آخر')),
                ('monthly_report_comparison_1_4', models.FloatField(blank=True, editable=False, null=True, verbose_name='مقایسه آخرین گزارش ماهانه موجود')),
                ('monthly_report_comparison_2_5', models.FloatField(blank=True, editable=False, null=True, verbose_name='مقایسه گزارش ماهانه یکی مانده به آخر')),
                ('monthly_report_comparison_3_6', models.FloatField(blank=True, editable=False, null=True, verbose_name='مقایسه گزارش ماهانه دوتا مانده به آخر')),
                ('seasonal_report_spring_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ گزارش فصلی بهار')),
                ('seasonal_report_spring_date_order', models.SmallIntegerField(default=1, editable=False)),
                ('seasonal_report_spring_percentage', models.FloatField(blank=True, editable=False, null=True, verbose_name='درصد گزارش فصلی بهار')),
                ('seasonal_report_spring_color', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='رنگ گزارش فصلی بهار')),
                ('seasonal_report_summer_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ گزارش فصلی تابستان')),
                ('seasonal_report_summer_date_order', models.SmallIntegerField(default=2, editable=False)),
                ('seasonal_report_summer_percentage', models.FloatField(blank=True, editable=False, null=True, verbose_name='درصد گزارش فصلی تابستان')),
                ('seasonal_report_summer_color', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='رنگ گزارش فصلی تابستان')),
                ('seasonal_report_fall_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ گزارش فصلی پاییز')),
                ('seasonal_report_fall_date_order', models.SmallIntegerField(default=3, editable=False)),
                ('seasonal_report_fall_percentage', models.FloatField(blank=True, editable=False, null=True, verbose_name='درصد گزارش فصلی پاییز')),
                ('seasonal_report_fall_color', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='رنگ گزارش فصلی پاییز')),
                ('seasonal_report_winter_date', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='تاریخ گزارش فصلی زمستان')),
                ('seasonal_report_winter_date_order', models.SmallIntegerField(default=4, editable=False)),
                ('seasonal_report_winter_percentage', models.FloatField(blank=True, editable=False, null=True, verbose_name='درصد گزارش فصلی زمستان')),
                ('seasonal_report_winter_color', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='رنگ گزارش فصلی زمستان')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='codal.company', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
            },
        ),
    ]
