# Generated by Django 4.2.3 on 2023-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0010_alter_monthlyreport_options_companyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companylink',
            options={'ordering': ['badge'], 'verbose_name': 'لینک شرکت', 'verbose_name_plural': 'لینک شرکت ها'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'پروفایل شرکت', 'verbose_name_plural': 'پروفایل شرکت ها'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_fall_date_order',
            field=models.SmallIntegerField(blank=True, default=3, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_spring_date_order',
            field=models.SmallIntegerField(blank=True, default=1, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_summer_date_order',
            field=models.SmallIntegerField(blank=True, default=2, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_winter_date_order',
            field=models.SmallIntegerField(blank=True, default=4, editable=False, null=True),
        ),
    ]
