# Generated by Django 4.2.3 on 2023-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0011_alter_companylink_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='لینک جزئیات سازمان'),
        ),
        migrations.AlterField(
            model_name='companylink',
            name='link',
            field=models.CharField(max_length=2000, verbose_name='لینک'),
        ),
    ]
