# Generated by Django 4.2.3 on 2023-07-18 19:03

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0012_alter_company_link_alter_companylink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_fall_date',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2023, 7, 18), editable=False, null=True, verbose_name='تاریخ گزارش فصلی پاییز'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_spring_date',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2023, 7, 18), editable=False, null=True, verbose_name='تاریخ گزارش فصلی بهار'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_summer_date',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2023, 7, 18), editable=False, null=True, verbose_name='تاریخ گزارش فصلی تابستان'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_winter_date',
            field=django_jalali.db.models.jDateField(blank=True, default=datetime.date(2023, 7, 18), editable=False, null=True, verbose_name='تاریخ گزارش فصلی زمستان'),
        ),
    ]
