# Generated by Django 4.2.3 on 2023-07-18 19:04

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0013_alter_companyprofile_seasonal_report_fall_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_fall_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ گزارش فصلی پاییز'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_spring_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ گزارش فصلی بهار'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_summer_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ گزارش فصلی تابستان'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='seasonal_report_winter_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ گزارش فصلی زمستان'),
        ),
    ]
