# Generated by Django 4.2.3 on 2023-07-18 20:17

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0014_alter_companyprofile_seasonal_report_fall_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='date_finished',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان پایان عملیات'),
        ),
    ]
