# Generated by Django 4.2.3 on 2023-07-19 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0015_alter_company_created_at_alter_company_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonalreport',
            options={'ordering': ['-season_reported_date'], 'verbose_name': 'گزارش فصلی', 'verbose_name_plural': 'گزارش فصلی'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='date_finished',
        ),
    ]
