# Generated by Django 4.2.3 on 2023-07-19 15:16

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0016_alter_seasonalreport_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='monthly_report_1_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ آخرین گزارش ماهانه موجود'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='monthly_report_2_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ گزارش ماهانه یکی مانده به آخر'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='monthly_report_3_date',
            field=django_jalali.db.models.jDateField(blank=True, editable=False, null=True, verbose_name='تاریخ گزارش ماهانه دوتا مانده به آخر'),
        ),
    ]
