# Generated by Django 4.2.3 on 2023-07-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0017_alter_companyprofile_monthly_report_1_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalreport',
            name='operating_ratio',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='تقسیم سود عملیاتی بر سود یا زیان ناخالص'),
        ),
    ]
