# Generated by Django 4.2.3 on 2023-07-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codal', '0018_seasonalreport_operating_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalreport',
            name='operating_ratio',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='تقسیم درآمد های عملیاتی بر سود یا زیان ناخالص'),
        ),
    ]
